name: test_firebase_login_and_create
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  firebase_core: ^2.31.0
  flutter_riverpod: ^2.5.1
  cloud_firestore: ^4.17.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true
